name_button = ["TRY","TOOLS","ENTITIES","EXIT"] 
id_current = 0
fase_menu = "start"
exit_game = false
start_game = false
fade_alpha = 1
fade_title = 0
config = false
volume_config = true
enemy_bar = false
color_patern = [c_white,c_white,c_white,c_white,c_white,c_white,c_white,c_white,c_white,c_white,c_white]
t_ani = 0
invert = 1
tool_menu_open = false
tool_description_eng = ["A sharp piece of wood use to deal with profane and unknow entities","A way to deal with wounds","A sharped blade to deal with more mundane entities"]
